//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServicioModulo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioModulo.IServicioModulo")]
    public interface IServicioModulo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModulo/ObtenerModulo", ReplyAction="http://tempuri.org/IServicioModulo/ObtenerModuloResponse")]
        int ObtenerModulo(int divisor, int dividendo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModulo/ObtenerModulo", ReplyAction="http://tempuri.org/IServicioModulo/ObtenerModuloResponse")]
        System.Threading.Tasks.Task<int> ObtenerModuloAsync(int divisor, int dividendo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioModuloChannel : Cliente.ServicioModulo.IServicioModulo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioModuloClient : System.ServiceModel.ClientBase<Cliente.ServicioModulo.IServicioModulo>, Cliente.ServicioModulo.IServicioModulo {
        
        public ServicioModuloClient() {
        }
        
        public ServicioModuloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioModuloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioModuloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioModuloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ObtenerModulo(int divisor, int dividendo) {
            return base.Channel.ObtenerModulo(divisor, dividendo);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerModuloAsync(int divisor, int dividendo) {
            return base.Channel.ObtenerModuloAsync(divisor, dividendo);
        }
    }
}
